# Generated by Django 4.0.4 on 2022-06-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('duration', models.IntegerField(max_length=10000)),
                ('date_started', models.DateField(auto_now_add=True)),
                ('date_ended', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
