# Generated by Django 4.0.4 on 2022-06-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
        migrations.AddField(
            model_name='reservation',
            name='occupation',
            field=models.CharField(default='none', max_length=10000),
        ),
    ]
