# Generated by Django 4.0.4 on 2022-06-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_reservation_duration_reservation_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(default='0'),
        ),
    ]
